const ERRORS = {
  PHONE_NUMBER_MANDATORY: 'Bad Input Request - One Phone number is mandatory to create a contact',
  INVALID_ID_KEY_PHONE: 'Bad Input Request - Invalid key _id in phone list',
  MISSING_PHONE_NUMBER: 'Bad Input Request - Phone number is missing in one or more phone list',
  MISSING_PHONE_TAG: 'Bad Input Request - Phone number tag is missing in one or more phone list',
  DUPLICATE_ENTRY_PHONE: 'Bad Input Request - Phone number and tag has duplicate entries',
  INVALID_PHONE_NUMBER: 'Bad Input Request - One or more phone number is invalid',
  INVALID_ID_KEY_EMAIL: 'Bad Input Request - Invalid key _id in email list',
  MISSING_EMAIL_ID: 'Bad Input Request - Email Id is missing in one or more email list',
  MISSING_EMAIL_TAG: 'Bad Input Request - Email Id tag is missing in one or more email list',
  DUPLICATE_ENTRY_EMAIL: 'Bad Input Request - Email id and tag has duplicate entries',
  INVALID_EMAIL_ID: 'Bad Input Request - One or more email id is invalid',
  BAD_INPUT_REQUEST: 'Bad Input Request.',
  INVALID_ID_KEY: 'Bad Input Request - Invalid key _id',
  NAME_MANDATORY: 'Bad Input Request - Name is mandatory',
  NAME_EXISTS: 'Bad Input Request - Name already exists',
  INVALID_ID: 'Invalid Id',
  MISSING_CONTACT_ID: 'Contact ID not found in request body',
  REQUEST_ID_MISMATCH: 'Request Param ID did not match with the request body ID',
  CANNOT_ADD_CONTACT: 'Bad Input Request - Contacts cannot be added while creating a group',
  GROUP_EXISTS: 'Group with this name already exists',
  INVALID_GROUP_ID: 'Invalid Contact Group Id',
  ID_MANDATORY: 'Bad request input - _id is mandatory',
  INVALID_KEY_CONTACTS: 'Bad request input - Invalid key contacts',
  CONTACT_LIST_MANDATORY: 'Bad request input - Contacts list is mandatory',
  DUPLICATE_CONTACT_LIST: 'Bad request input - Contacts list has duplicate elements',
  MAX_CONTACT_EXCEEDS: 'Bad request input - Contacts list length exceeds 100',
  INVALID_CONTACT_IDS: 'Bad request input - One or more contact id(s) invalid',
  INVALID_VALUE_NAME: 'Bad request input - Invalid value for name',
  CONTACT_ID_EXISTS: 'Bad request input - Contact Id already exists in the group',
};

module.exports = {
  ERRORS,
};
